module.exports = {
  light: {
    '@layout-body-background': '@white',
    '@primary-color': '#4a90e2',
    '@file-preview-border': '#eaeaea',
    '@file-preview-background': '#fbfbfb',
    '@rapid-a': '#f0f9ff',
    '@rapid-b': '#4e4e4e',
    '@rapid-c': '#1d4371',
    '@rapid-d': '#f5f5f5',
    '@rapid-e': '#d9e9fa',
    '@header-selected-color': '#1d4371',
    '@header-border-color': '#e2e2e2',
    '@code-viewer-bg': '#fff',
  },
  dark: {
    '@body-background': '@black',
    '@btn-primary-color': '@white',
    '@component-background': '#001025',
    '@icon-color-hover': 'fade(@white, 75%)',
    '@heading-color': 'fade(@white, 85%)',
    '@text-color': '#C6C7C8',
    '@text-color-secondary': 'fade(@white, 45%)',
    '@border-color-base': '#434343',
    '@border-style-base': 'solid',
    '@layout-body-background': '#001025',
    '@layout-header-background': '@component-background',
    '@layout-sider-background': '@component-background',
    '@layout-trigger-background': '@component-background',
    '@font-family': "'Lato', sans-serif",
    '@font-feature-settings-base': 'tnum',
    '@disabled-color': 'fade(@white, 30%)',
    '@disabled-color-dark': 'fade(@white, 30%)',
    '@outline-blur-size': '0',
    '@background-color-light': 'fade(@white, 4%)',
    '@background-color-base': 'fade(@white, 8%)',
    '@rapid-a': '@component-background',
    '@rapid-b': '@white',
    '@rapid-c': '@white',
    '@rapid-d': '@component-background',
    '@rapid-e': '@component-background',
    '@item-hover-bg': 'fade(@white, 8%)',
    '@shadow-color': 'rgba(0, 0, 0, 0.45)',
    '@shadow-1-up':
      '0 -6px 16px -8px rgba(0, 0, 0, 0.24), 0 -9px 28px 0 rgba(0, 0, 0, 0.15), 0 -12px 48px 16px rgba(0, 0, 0, 0.09)',
    '@shadow-1-down':
      '0 6px 16px -8px rgba(0, 0, 0, 0.24), 0 9px 28px 0 rgba(0, 0, 0, 0.15), 0 12px 48px 16px rgba(0, 0, 0, 0.09)',
    '@shadow-1-left':
      '-6px 0 16px -8px rgba(0, 0, 0, 0.08), -9px 0 28px 0 rgba(0, 0, 0, 0.05), -12px 0 48px 16px rgba(0, 0, 0, 0.03)',
    '@shadow-1-right':
      '6px 0 16px -8px rgba(0, 0, 0, 0.24), 9px 0 28px 0 rgba(0, 0, 0, 0.15), 12px 0 48px 16px rgba(0, 0, 0, 0.09)',
    '@shadow-2':
      '0 3px 6px -4px rgba(0, 0, 0, 0.36), 0 6px 16px 0 rgba(0, 0, 0, 0.24), 0 9px 28px 8px rgba(0, 0, 0, 0.15)',
    '@btn-default-bg': 'transparent',
    '@input-placeholder-color': 'fade(@white, 30%)',
    '@input-bg': 'transparent',
    '@select-item-selected-font-weight': '600',
    '@tooltip-bg': 'fade(@white, 90%)',
    '@menu-dark-submenu-bg': '@black',
    '@table-header-bg': '#1d1d1d',
    '@table-header-sort-bg': '#262626',
    '@table-body-sort-bg': 'fade(@white, 1%)',
    '@table-row-hover-bg': 'fade(@white, 8%)',
    '@badge-text-color': '@white',
    '@card-actions-background': 'fade(@white, 4%)',
    '@card-shadow':
      '0 1px 2px -2px rgba(0, 0, 0, 0.48), 0 3px 6px 0 rgba(0, 0, 0, 0.36), 0 5px 12px 4px rgba(0, 0, 0, 0.27)',
    '@avatar-bg': '#5a5a5a',
    '@pagination-item-bg-active': 'transparent',
    '@slider-rail-background-color': 'fade(@white, 20%)',
    '@slider-rail-background-color-hover': '@slider-rail-background-color',
    '@slider-track-background-color': '@primary-color',
    '@slider-handle-color': '@primary-color',
    '@skeleton-color': '#303030',
    '@alert-success-border-color': '@green-3',
    '@alert-success-bg-color': '@green-1',
    '@alert-info-border-color': '@blue-3',
    '@alert-info-bg-color': '@blue-1',
    '@alert-warning-border-color': '@gold-3',
    '@alert-warning-bg-color': '@gold-1',
    '@alert-error-border-color': '@red-3',
    '@alert-error-bg-color': '@red-1',
    '@zindex-modal': '1000',
    '@zindex-modal-mask': '1000',
    '@modal-header-bg': '@component-background',
    '@modal-footer-bg': 'transparent',
    '@modal-mask-bg': 'fade(@component-background, 45%)',
    '@wait-step-color': 'fade(@white, 45%)',
    '@wait-title-color': '@wait-step-color',
    '@header-selected-color': '#FFFFFF',
    '@header-border-color': '#012858',
    '@code-viewer-bg': '#000',
  },
};
